### ISSUE TITLE
Utility limits

### ISSUE THREAD

**Issue by shaikhnedab** [yonilerner/cs2-retakes-allocator#55] opened 2024-01-13 10:18 UTC
maximum no. of utility peer teams.
e.g whole team T can only have 2 flash and 1 smoke etc.

**Comment by yonilerner** [comment] 2024-01-13 20:47
Duplicate of https://github.com/yonilerner/cs2-retakes-allocator/discussions/21

**Closed by yonilerner** 2024-01-13 20:47 UTC
