### ISSUE TITLE
The regular buymenu bound to button B - can buy rifles during pistol rounds

### ISSUE THREAD

**Issue by Svampkant** [yonilerner/cs2-retakes-allocator#117] opened 2024-03-26 14:49 UTC
There is an issue with using the buymenu during pistol rounds. You can buy rifles but can't use them.
If you accidently buy an rifle during pistol rounds it will show that you have an rifle in your hand but it isn't in your "inventory".
To get pistol again you have to buy or pick up the pistol you dropped when you bought the rifle.

I dont know if there is an easy solution for this, but an workaround imo, could be to limit the money during pistol rounds to around 800 so the only weapons you can buy is pistols.

**Comment by yonilerner** [comment] 2024-04-01 06:56
Ya this is a tricky one. Im working on a better solution for the buy menu in general

**Comment by yonilerner** [comment] 2024-04-01 07:09
Im closing this issue since its a duplicate of https://github.com/yonilerner/cs2-retakes-allocator/issues/94 but i have not forgotten it. You can follow the other issue if you want to see progress updates

**Closed by yonilerner** 2024-04-01 07:09 UTC
